# Generated by Django 6.0.3 on 2026-04-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniconlineapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staffspecialty',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniconlineapi.staffprofile'),
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')])),
                ('is_active', models.BooleanField(default=True)),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniconlineapi.staffprofile')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('staff_profile', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=10)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliniconlineapi.workday')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('work_day', 'start_time')},
            },
        ),
    ]
