# Generated by Django 6.0.3 on 2026-04-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniconlineapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
