# Generated by Django 6.0.3 on 2026-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliniconlineapi', '0002_alter_workday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
    ]
