# Generated by Django 6.0.3 on 2026-04-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliniconlineapi', '0002_staffprofile_price_alter_staffspecialty_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='is_active',
        ),
    ]
